import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useTheme } from "next-themes";
import { Main } from "next/document";
import HomePage from "../../components/HomePage";
import Layout from "../../components/Layout";
import { useContext } from "react";
import { AuthContext } from "../../contexts/AuthContext";
import { useRouter } from "next/router";

export default function Home() {
  const { currentUser } = useContext(AuthContext);
  const router = useRouter();
  const ProtectedRoute = ({ children }) => {
    if (!currentUser) {
      router.push("/login");
      return null;
    }
    return children;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ProtectedRoute>
          <div className="text-black bg-[#f8fafc] pb-24 pt-36">
            <HomePage />
          </div>
        </ProtectedRoute>
      </Layout>
    </>
  );
}
